"""empty message

Revision ID: de17244d6d6e
Revises: 518f51c85992
Create Date: 2021-05-05 02:32:25.528419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de17244d6d6e'
down_revision = '518f51c85992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('echo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('echo_id', sa.String(length=256), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('echo_id'),
    sa.UniqueConstraint('echo_id')
    )
    op.drop_column('user', 'echo_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('echo_id', sa.VARCHAR(length=256), nullable=True))
    op.drop_table('echo')
    # ### end Alembic commands ###
